spring:
  main:
    web-application-type: none
logging:
  path: ../log
  file: ../log/buildpatch.log
  file.max-size: 10MB
  level:
    root: warn
  pattern:
    console: "%d [%t] %-5level : %msg%n"
    file: "%d %p %m%n"
patchproducer:
  tool-version: "3.5"
  product: "Cloud"
  product-version: "5.0"
  deploy-unit: "ScmFnd"
  deploy-unit-name: "供应链设置"
  deploy-unit-version: "5.0"
  temp-path: "/PatchTemp"
  temp-zip-path: "/PatchZipTemp/temp.zip"
  server-root: "root"
  db-root: "DBUpdateFiles"
  version: "1.0.4-BETA"
  # 可修改参数配置
  # 补丁输出目录
  patch-path: "/Patch"
  # 应用服务器后端文件目录
  server-path: "/publish/server/apps/scm"
  # 应用服务器前端文件目录
  web-path: "/publish/web/apps/scm"
  # DBO文件目录
  dbo-path: "/publish/server/apps/scm"
  # Data文件目录
  data-path: "/publish/tools/setup/db/scm"
  # iGIX元数据文件目录
  metadata-path: "/publish/metadata/apps/scm"
  # IDP元数据文件目录
  idp-path: "/idp/scm"
  # 交付物路径
  delivery-path: "D:/projects/Scm/delivery/Scm_All"
  # 默认起始日期
  default-begin: "2023-10-25 06:00"
  # 是否开启提交记录过滤
  commit-filter: true
  # 是否开启su过滤
  su-filter: true